from __future__ import annotations

from collections.abc import MutableSet
from typing import TypeAlias
import numpy as np
import numpy.typing as npt

Int32Array: TypeAlias = npt.NDArray[np.int32]
Int64Array: TypeAlias = npt.NDArray[np.int64]
Float32Array: TypeAlias = npt.NDArray[np.float32]


class pyLSH:
    def __init__(self, K: int, L: int, THREADS: int) -> None: ...
    def remove(self, fp: Int32Array, item_id: int) -> None: ...
    def insert(self, fp: Int32Array, item_id: int) -> None: ...
    def insert_multi(self, fp: Int32Array, N: int) -> None: ...
    def query(self, fp: Int32Array) -> set[int]: ...
    def query_multi(self, fp: Int32Array, N: int) -> set[int]: ...
    def query_multi_mask(
        self, fp: Int32Array, mask: Float32Array, M: int, N: int
    ) -> None: ...
    def accidental_match(
        self, labels: Int64Array, samples: MutableSet[int], N: int
    ) -> None: ...
    def multi_label(
        self, labels: Int64Array, samples: MutableSet[int]
    ) -> tuple[list[int], Float32Array]: ...
    def multi_label_nonunion(
        self, labels: Int64Array, samples: Int64Array
    ) -> tuple[Int64Array, Float32Array]: ...
    def query_matrix(
        self, fp: Int32Array, labels: Int32Array, N: int, total_size: int
    ) -> tuple[Int64Array, int]: ...
    def print_stats(self) -> list[int]: ...
    def clear(self) -> None: ...
